apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-deployment
  labels:
    app: scc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scc
  template:
    metadata:
      labels:
        app: scc
    spec:
      terminationGracePeriodSeconds: 1
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL..."
              until nc -zv $CLOUD_PG_HOST $CLOUD_PG_PORT; do
                echo "PostgreSQL not ready, sleeping 5s..."
                sleep 5
              done
              echo "PostgreSQL is ready!"
          envFrom:
            - secretRef:
                name: auth-api-cloud-secrets
      containers:
        - name: scc
          image: dev2c1vieira/kubernetes-auth-microservice:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          envFrom:
            - secretRef:
                name: auth-api-cloud-secrets
